In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
from torch import nn
import torch.nn.functional as F
from typing import Dict, List
import enum
from enum import Enum
import numpy as np

In [9]:
loss = nn.CrossEntropyLoss(reduction='none')#'mean')
x =  torch.tensor([[0.1 ,0.9, 0.3],[0.9, 0.1,0.7]]).unsqueeze_(0)
x0 = [0.1 , 0.9]
softmax_p =-np.log(np.exp(x0)/sum(np.exp(x0)))

target_class = torch.tensor([1, 0 ,1]).unsqueeze_(0)
print(f"{softmax_p[1]=}")
print(f"{x.shape=}")
print(f"{x=}")
print(f"{loss(x,target_class)=}")
print(f"{loss(x,target_class).shape=}")

softmax_p[1]=0.3711006659477778
x.shape=torch.Size([1, 2, 3])
x=tensor([[[0.1000, 0.9000, 0.3000],
         [0.9000, 0.1000, 0.7000]]])
loss(x,target_class)=tensor([[0.3711, 0.3711, 0.5130]])
loss(x,target_class).shape=torch.Size([1, 3])


In [4]:
np.exp(0.3133)

1.3679318490315369

In [5]:
(-0.9 -0.9  -0.7) /3 

-0.8333333333333334

In [6]:
np.exp(0.3711)

1.4493279989401402

In [7]:
x = [0.0 ,0.0 , 1.0]
print(np.exp(x)/sum(np.exp(x)))
print(1.0/(2 + np.exp(1)))
print(np.exp(1)/(2 + np.exp(1)))

[0.21194156 0.21194156 0.57611688]
0.21194155761708547
0.5761168847658291


In [23]:
x =  torch.tensor([[0.1 ,0.9, 0.3],[0.9, 0.1,0.7]]).unsqueeze_(0)
print(f"{x.shape=}")
print(f"{x=}")
y= torch.mean(x, dim=0)
print(f"{y=}")
print(f"{y.shape=}")

z= torch.mean(x)
print(f"{z=}")
print(f"{z.shape=}")

x.shape=torch.Size([1, 2, 3])
x=tensor([[[0.1000, 0.9000, 0.3000],
         [0.9000, 0.1000, 0.7000]]])
y=tensor([[0.1000, 0.9000, 0.3000],
        [0.9000, 0.1000, 0.7000]])
y.shape=torch.Size([2, 3])
z=tensor(0.5000)
z.shape=torch.Size([])


In [18]:
torch.mean?

In [30]:
x



tensor([[[0.1000, 0.9000, 0.3000],
         [0.9000, 0.1000, 0.7000]]])

In [31]:
x+1

tensor([[[1.1000, 1.9000, 1.3000],
         [1.9000, 1.1000, 1.7000]]])