In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
from torch import nn
import torch.nn.functional as F
from typing import Dict, List
import enum
from enum import Enum
import numpy as np

In [7]:
x = torch.zeros([3,1,3])
y = torch.ones([3,1,3])
z = torch.cat((x,y),1)
print(f"{z.shape}")
print(f"{z}")

torch.Size([3, 2, 3])
tensor([[[0., 0., 0.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [1., 1., 1.]]])


In [14]:
x = torch.tensor([1,2,3]).unsqueeze_(-1).unsqueeze_(-1)
print(f"{x.shape=}")
x2 = x.repeat(2,1,1)
print(f"{x2.shape=}")
assert torch.all(x.eq(x2))

x.shape=torch.Size([3, 1, 1])
x2.shape=torch.Size([6, 1, 1])


RuntimeError: The size of tensor a (3) must match the size of tensor b (6) at non-singleton dimension 0

In [15]:
from dsin.ae.si_net import *

In [23]:
repr(SiNet(SiNetChannelIn.WithSideInformation,True))

'SiNet(\n  (model): Sequential(\n    (0): ChangeImageStatsToKitti()\n    (1): Conv2d(6, 32, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1], padding_mode=replicate)\n    (2): LeakyReLU(negative_slope=0.2)\n    (3): Conv2d(32, 32, kernel_size=[3, 3], stride=(1, 1), padding=[2, 2], dilation=(2, 2), padding_mode=replicate)\n    (4): LeakyReLU(negative_slope=0.2)\n    (5): Conv2d(32, 32, kernel_size=[3, 3], stride=(1, 1), padding=[4, 4], dilation=(4, 4), padding_mode=replicate)\n    (6): LeakyReLU(negative_slope=0.2)\n    (7): Conv2d(32, 32, kernel_size=[3, 3], stride=(1, 1), padding=[8, 8], dilation=(8, 8), padding_mode=replicate)\n    (8): LeakyReLU(negative_slope=0.2)\n    (9): Conv2d(32, 32, kernel_size=[3, 3], stride=(1, 1), padding=[16, 16], dilation=(16, 16), padding_mode=replicate)\n    (10): LeakyReLU(negative_slope=0.2)\n    (11): Conv2d(32, 32, kernel_size=[3, 3], stride=(1, 1), padding=[32, 32], dilation=(32, 32), padding_mode=replicate)\n    (12): LeakyReLU(negative_slope=0.

In [24]:
torch.tensor(
                    [93.70454143384742, 98.28243432206516, 94.84678088809876],
                    dtype=torch.float32,
                ).repeat(2)

tensor([93.7045, 98.2824, 94.8468, 93.7045, 98.2824, 94.8468])

In [9]:
loss = nn.CrossEntropyLoss(reduction='none')#'mean')
x =  torch.tensor([[0.1 ,0.9, 0.3],[0.9, 0.1,0.7]]).unsqueeze_(0)
x0 = [0.1 , 0.9]
softmax_p =-np.log(np.exp(x0)/sum(np.exp(x0)))

target_class = torch.tensor([1, 0 ,1]).unsqueeze_(0)
print(f"{softmax_p[1]=}")
print(f"{x.shape=}")
print(f"{x=}")
print(f"{loss(x,target_class)=}")
print(f"{loss(x,target_class).shape=}")

softmax_p[1]=0.3711006659477778
x.shape=torch.Size([1, 2, 3])
x=tensor([[[0.1000, 0.9000, 0.3000],
         [0.9000, 0.1000, 0.7000]]])
loss(x,target_class)=tensor([[0.3711, 0.3711, 0.5130]])
loss(x,target_class).shape=torch.Size([1, 3])


In [ ]:
x = 

In [4]:
np.exp(0.3133)

1.3679318490315369

In [5]:
(-0.9 -0.9  -0.7) /3 

-0.8333333333333334

In [6]:
np.exp(0.3711)

1.4493279989401402

In [7]:
x = [0.0 ,0.0 , 1.0]
print(np.exp(x)/sum(np.exp(x)))
print(1.0/(2 + np.exp(1)))
print(np.exp(1)/(2 + np.exp(1)))

[0.21194156 0.21194156 0.57611688]
0.21194155761708547
0.5761168847658291


In [23]:
x =  torch.tensor([[0.1 ,0.9, 0.3],[0.9, 0.1,0.7]]).unsqueeze_(0)
print(f"{x.shape=}")
print(f"{x=}")
y= torch.mean(x, dim=0)
print(f"{y=}")
print(f"{y.shape=}")

z= torch.mean(x)
print(f"{z=}")
print(f"{z.shape=}")

x.shape=torch.Size([1, 2, 3])
x=tensor([[[0.1000, 0.9000, 0.3000],
         [0.9000, 0.1000, 0.7000]]])
y=tensor([[0.1000, 0.9000, 0.3000],
        [0.9000, 0.1000, 0.7000]])
y.shape=torch.Size([2, 3])
z=tensor(0.5000)
z.shape=torch.Size([])


In [18]:
torch.mean?

In [30]:
x



tensor([[[0.1000, 0.9000, 0.3000],
         [0.9000, 0.1000, 0.7000]]])

In [31]:
x+1

tensor([[[1.1000, 1.9000, 1.3000],
         [1.9000, 1.1000, 1.7000]]])

In [68]:
 x = nn.Conv2d(
                    in_channels=32,
                    out_channels=32,
                    kernel_size=[3, 3],
                  
                )

In [69]:

with torch.no_grad():
    w = torch.eye(
        n=x.kernel_size[0], dtype=torch.float32
    ).repeat(x.weight.shape[0], x.weight.shape[1], 1, 1)

    x.weight = nn.Parameter(w)



In [70]:
for param in x.parameters():
    print(param)

Parameter containing:
tensor([[[[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]],

         [[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]],

         [[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]],

         ...,

         [[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]],

         [[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]],

         [[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]]],


        [[[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]],

         [[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]],

         [[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]],

         ...,

         [[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]],

         [[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]],

         [[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]]],


        [[[1., 0., 0.],
          [0., 1., 0.],
        

In [57]:
x.weight

Parameter containing:
tensor([[[[-0.0576,  0.1122,  0.0262],
          [ 0.0661, -0.1964, -0.1904],
          [-0.0321,  0.0543, -0.1121]],

         [[ 0.0674,  0.0942, -0.0026],
          [-0.1720,  0.0449, -0.2070],
          [ 0.1315, -0.1814, -0.0462]]],


        [[[ 0.1637,  0.1197, -0.0227],
          [-0.0492, -0.2256, -0.0596],
          [-0.1591,  0.1324,  0.2147]],

         [[ 0.1496,  0.0868,  0.2316],
          [ 0.2255,  0.0375, -0.2177],
          [ 0.1986,  0.1989,  0.0149]]]], requires_grad=True)

In [43]:
x = torch.tensor([1, 2, 3])
print(x.repeat(4, 2))
print(x.shape)
print(x.repeat(4, 2, 1).size())


tensor([[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]])
torch.Size([3])
torch.Size([4, 2, 3])


In [67]:
for i,t in enumerate([54,6,7,4]):
    print(f"{i=}")
    print(f"{t=}")
    
    

i=0
t=54
i=1
t=6
i=2
t=7
i=3
t=4
