In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
from torch import nn
import torch.nn.functional as F
from typing import Dict, List
import enum
from enum import Enum

In [3]:
from dsin.ae.importance_map import *

In [4]:
x = torch.tensor(
            [[[0, 0, 0], [torch.log(torch.tensor(0.5 )), torch.log(torch.tensor(0.5 )), torch.log(torch.tensor(0.5 ))]], [[3, 3, 3], [4, 4, 4]]], dtype=torch.float32
        )

y = ImportanceMapMult(use_map=True)(x)
y_ = 0.01 * torch.tensor([[[3, 3, 3], [8, 8, 8]]], dtype=torch.float32
        )
print(x)
print(y)
print(y_)

> /mnt/code/repos/tDSIN/src/dsin/ae/importance_map.py(72)forward()
     71         import ipdb; ipdb.set_trace()
---> 72         importance_map.unsqueeze_(CHANNEL_DIM)  # N1HW
     73 

ipdb> cl_param
tensor([[[0.]]], grad_fn=<ViewBackward>)
ipdb> importance_map
tensor([[0.5000, 0.5000, 0.5000],
        [0.9526, 0.9526, 0.9526]])
ipdb> n
> /mnt/code/repos/tDSIN/src/dsin/ae/importance_map.py(74)forward()
     73 
---> 74         z = x[:, MAP_CHANNEL + 1 :, ...]
     75 

ipdb> n
> /mnt/code/repos/tDSIN/src/dsin/ae/importance_map.py(76)forward()
     75 
---> 76         diff = importance_map - cl_param
     77 

ipdb> n
> /mnt/code/repos/tDSIN/src/dsin/ae/importance_map.py(78)forward()
     77 
---> 78         out_map = MinMaxMap.apply(diff)
     79 

ipdb> diff
tensor([[[0.5000, 0.5000, 0.5000]],

        [[0.9526, 0.9526, 0.9526]]], grad_fn=<SubBackward0>)
ipdb> n
> /mnt/code/repos/tDSIN/src/dsin/ae/importance_map.py(80)forward()
     78         out_map = MinMaxMap.apply(diff)
     79 

In [7]:
0.6931/2


0.34655

In [6]:
torch.exp(-1 * torch.log(torch.tensor(0.5 )))

tensor(2.)