In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
#export
from dsin.ae.probclass import *

In [14]:
x= nn.Conv3d(
    in_channels= 6,
    out_channels= 6,
    kernel_size= (2,3,3),
    stride=1,
    padding=0,
    dilation=1,
    groups=1,
    bias=True,
    padding_mode='zeros',
)
x.weight.shape


torch.Size([6, 6, 2, 3, 3])

In [5]:
# !python notebook2script.py nb__test_probclass.ipynb

In [15]:
NOF_CENTERS = 6 
pc = ProbClassifier(classifier_in_channels=32, classifier_out_channels=NOF_CENTERS ,kernel_size=3)
x = torch.rand([1,2,32,5,5])
# nt(pc)
pc(x)


torch.Size([24, 32, 3, 3, 3])
torch.Size([1, 1, 2, 3, 3])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 2

In [19]:
x= torch.rand([2,3,3])
print(x)
print(x.shape)
print(x.unsqueeze_(0))
print(x.shape)
x.unsqueeze_(0)
print(x.shape)


tensor([[[0.0886, 0.5137, 0.3534],
         [0.9377, 0.9737, 0.8374],
         [0.3934, 0.8077, 0.6093]],

        [[0.7077, 0.8381, 0.0814],
         [0.0273, 0.0209, 0.7208],
         [0.8733, 0.6213, 0.4273]]])
torch.Size([2, 3, 3])
tensor([[[[0.0886, 0.5137, 0.3534],
          [0.9377, 0.9737, 0.8374],
          [0.3934, 0.8077, 0.6093]],

         [[0.7077, 0.8381, 0.0814],
          [0.0273, 0.0209, 0.7208],
          [0.8733, 0.6213, 0.4273]]]])
torch.Size([1, 2, 3, 3])
torch.Size([1, 1, 2, 3, 3])


In [23]:
mask = MaskedConv3d.create_maskB(3,(2,3,3))
mask

tensor([[[[[1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.]],

          [[1., 1., 1.],
           [1., 1., 0.],
           [0., 0., 0.]]]]])

In [25]:
mask = MaskedConv3d.old_create_maskB(3,(2,3,3))
mask

tensor([[[[[1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.]],

          [[1., 1., 1.],
           [1., 1., 0.],
           [0., 0., 0.]]]]])