In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
#export
from dsin.ae.probclass import *

In [14]:
x= nn.Conv3d(
    in_channels= 6,
    out_channels= 6,
    kernel_size= (2,3,3),
    stride=1,
    padding=0,
    dilation=1,
    groups=1,
    bias=True,
    padding_mode='zeros',
)
x.weight.shape


torch.Size([6, 6, 2, 3, 3])

In [5]:
# !python notebook2script.py nb__test_probclass.ipynb

In [15]:
NOF_CENTERS = 6 
pc = ProbClassifier(classifier_in_channels=32, classifier_out_channels=NOF_CENTERS ,kernel_size=3)
x = torch.rand([1,2,32,5,5])
# nt(pc)
pc(x)


torch.Size([24, 32, 3, 3, 3])
torch.Size([1, 1, 2, 3, 3])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 2

In [19]:
x= torch.rand([2,3,3])
print(x)
print(x.shape)
print(x.unsqueeze_(0))
print(x.shape)
x.unsqueeze_(0)
print(x.shape)


tensor([[[0.0886, 0.5137, 0.3534],
         [0.9377, 0.9737, 0.8374],
         [0.3934, 0.8077, 0.6093]],

        [[0.7077, 0.8381, 0.0814],
         [0.0273, 0.0209, 0.7208],
         [0.8733, 0.6213, 0.4273]]])
torch.Size([2, 3, 3])
tensor([[[[0.0886, 0.5137, 0.3534],
          [0.9377, 0.9737, 0.8374],
          [0.3934, 0.8077, 0.6093]],

         [[0.7077, 0.8381, 0.0814],
          [0.0273, 0.0209, 0.7208],
          [0.8733, 0.6213, 0.4273]]]])
torch.Size([1, 2, 3, 3])
torch.Size([1, 1, 2, 3, 3])


In [23]:
mask = MaskedConv3d.create_maskB(3,(2,3,3))
mask

tensor([[[[[1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.]],

          [[1., 1., 1.],
           [1., 1., 0.],
           [0., 0., 0.]]]]])

In [25]:
mask = MaskedConv3d.old_create_maskB(3,(2,3,3))
mask

tensor([[[[[1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.]],

          [[1., 1., 1.],
           [1., 1., 0.],
           [0., 0., 0.]]]]])

In [68]:

x= nn.Conv2d(
    in_channels=2 ,
    out_channels=2 ,
    kernel_size=4,
    stride=1,
    padding=0,
    dilation=1,
    groups=1,
    bias=True,
    padding_mode='zeros',
)
x.weight

Parameter containing:
tensor([[[[ 0.0588,  0.0571, -0.1676,  0.0686],
          [ 0.1428,  0.1171,  0.0685,  0.0830],
          [-0.0068, -0.0040,  0.1743,  0.1358],
          [-0.1058, -0.0221, -0.1040,  0.0103]],

         [[-0.1713, -0.1507,  0.1251, -0.1379],
          [-0.0006, -0.1720, -0.1321, -0.1322],
          [-0.0367,  0.1609, -0.0794,  0.1686],
          [-0.0014, -0.0198,  0.0151,  0.0524]]],


        [[[ 0.1281, -0.0693, -0.1446,  0.1368],
          [ 0.0291, -0.1728, -0.1646, -0.1740],
          [-0.0024, -0.1090, -0.1271,  0.1709],
          [ 0.0709,  0.0357,  0.1659, -0.1533]],

         [[-0.0885,  0.0528, -0.0274,  0.1218],
          [-0.1486, -0.0270,  0.0835,  0.1381],
          [-0.0306, -0.1582, -0.0018,  0.1405],
          [-0.0026, -0.0534, -0.0297, -0.0437]]]], requires_grad=True)

In [34]:
t.values()

RuntimeError: Could not run 'aten::values' with arguments from the 'CPUTensorId' backend. 'aten::values' is only available for these backends: [SparseCPUTensorId, VariableTensorId].

In [86]:
x = torch.ones([2, 2, 4, 3])
y= torch.ones([3])
print(x.shape[-1])
print(x)

print(y, y.shape, y.unsqueeze_(0), y.shape)

3
tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])
tensor([[1., 1., 1.]]) torch.Size([3]) tensor([[1., 1., 1.]]) torch.Size([1, 3])


In [87]:
from dsin.ae.quantizer_imgcomp import *


In [100]:
a = Quantizer(num_centers=5,
            centers_initial_range=(0,10),
            centers_regularization_factor= 0.1,
            sigma=0.1)

x = torch.round(torch.rand([3,2,2,2])*10)
print(x)
print(a.centers)
x_soft, x_hard, x_index_of_center =  a(x)
print(x_hard)
print(x_index_of_center)
print(x_soft)


tensor([[[[ 5.,  1.],
          [ 7.,  6.]],

         [[ 3.,  1.],
          [ 4.,  5.]]],


        [[[ 7.,  4.],
          [ 1.,  2.]],

         [[ 0.,  4.],
          [ 9., 10.]]],


        [[[ 9.,  8.],
          [ 2.,  4.]],

         [[ 9.,  7.],
          [ 1.,  0.]]]])
Parameter containing:
tensor([3.1101, 4.7601, 6.6034, 8.7651, 9.6800], requires_grad=True)
tensor([[[4.7601, 3.1101, 6.6034, 6.6034],
         [3.1101, 3.1101, 4.7601, 4.7601]],

        [[6.6034, 4.7601, 3.1101, 3.1101],
         [3.1101, 4.7601, 8.7651, 9.6800]],

        [[8.7651, 8.7651, 3.1101, 4.7601],
         [8.7651, 6.6034, 3.1101, 3.1101]]], grad_fn=<IndexBackward>)
tensor([[[[1, 0],
          [2, 2]],

         [[0, 0],
          [1, 1]]],


        [[[2, 1],
          [0, 0]],

         [[0, 1],
          [3, 4]]],


        [[[3, 3],
          [0, 1]],

         [[3, 2],
          [0, 0]]]])
tensor([[[4.7601, 3.1101, 6.6034, 6.6034],
         [3.1101, 3.1101, 4.7601, 4.7601]],

        [[6.6034, 

In [101]:
from dsin.ae.autoencoder_imgcomp import *
enc = Encoder.create_module_from_const()


In [102]:
x = torch.rand([5,3,30,30])

In [103]:
x.shape

torch.Size([5, 3, 30, 30])

In [105]:
y=enc(x)

RuntimeError: The size of tensor a (8) must match the size of tensor b (30) at non-singleton dimension 3