In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
from torch import nn
from torch.nn import functional as F 
from torchvision.ops import roi_align

# Extracting a patch using boxes

In [3]:
x =torch.ceil(torch.rand(1,3,3,3)*20)
print(f"{x.shape=}")
print(f"{x=}")
out  =roi_align(
    x,
    [torch.tensor([[-0.5,-0.5,2.5,2.5]])],
    output_size = (3,3),
    spatial_scale=1.0,
    sampling_ratio=-1,
    aligned=False,
)
print(f"{out=}")


x.shape=torch.Size([1, 3, 3, 3])
x=tensor([[[[ 5., 17., 10.],
          [17.,  9.,  3.],
          [11.,  3.,  7.]],

         [[ 2., 17.,  7.],
          [16., 11.,  8.],
          [10., 12.,  7.]],

         [[10.,  9.,  2.],
          [ 4.,  6., 17.],
          [12., 18., 10.]]]])
out=tensor([[[[ 5., 17., 10.],
          [17.,  9.,  3.],
          [11.,  3.,  7.]],

         [[ 2., 17.,  7.],
          [16., 11.,  8.],
          [10., 12.,  7.]],

         [[10.,  9.,  2.],
          [ 4.,  6., 17.],
          [12., 18., 10.]]]])


#  Extracting multiple boxes from tensor index to roi-index

In [120]:
x =torch.linspace(start=0 , end = 3*6*6-1 , steps =3*6*6 )
x= x.view(1,3,6,6)
x

tensor([[[[  0.,   1.,   2.,   3.,   4.,   5.],
          [  6.,   7.,   8.,   9.,  10.,  11.],
          [ 12.,  13.,  14.,  15.,  16.,  17.],
          [ 18.,  19.,  20.,  21.,  22.,  23.],
          [ 24.,  25.,  26.,  27.,  28.,  29.],
          [ 30.,  31.,  32.,  33.,  34.,  35.]],

         [[ 36.,  37.,  38.,  39.,  40.,  41.],
          [ 42.,  43.,  44.,  45.,  46.,  47.],
          [ 48.,  49.,  50.,  51.,  52.,  53.],
          [ 54.,  55.,  56.,  57.,  58.,  59.],
          [ 60.,  61.,  62.,  63.,  64.,  65.],
          [ 66.,  67.,  68.,  69.,  70.,  71.]],

         [[ 72.,  73.,  74.,  75.,  76.,  77.],
          [ 78.,  79.,  80.,  81.,  82.,  83.],
          [ 84.,  85.,  86.,  87.,  88.,  89.],
          [ 90.,  91.,  92.,  93.,  94.,  95.],
          [ 96.,  97.,  98.,  99., 100., 101.],
          [102., 103., 104., 105., 106., 107.]]]])

In [121]:
patch_w = 2
patch_h = 2
offsets_w = [torch.tensor(0),torch.tensor(2),torch.tensor(4)]*3
offsets_h = [torch.tensor(0)]*3+[torch.tensor(2)]*3+[torch.tensor(4)]*3
l = torch.tensor([[0,-0.5+offset_w,-0.5+offset_h,-0.5+offset_w +patch_w,-0.5+offset_h+patch_h] 
                  for (offset_h,offset_w) in zip(offsets_h,offsets_w) ])
     

out  =roi_align(
    x,
    l,
    output_size = (patch_h,patch_w),
    spatial_scale=1.0,
    sampling_ratio=-1,
    aligned=False,
)
print(f"{out=}")
print(f"{x.shape=}")
print(f"{out.shape=}")

out=tensor([[[[  0.,   1.],
          [  6.,   7.]],

         [[ 36.,  37.],
          [ 42.,  43.]],

         [[ 72.,  73.],
          [ 78.,  79.]]],


        [[[  2.,   3.],
          [  8.,   9.]],

         [[ 38.,  39.],
          [ 44.,  45.]],

         [[ 74.,  75.],
          [ 80.,  81.]]],


        [[[  4.,   5.],
          [ 10.,  11.]],

         [[ 40.,  41.],
          [ 46.,  47.]],

         [[ 76.,  77.],
          [ 82.,  83.]]],


        [[[ 12.,  13.],
          [ 18.,  19.]],

         [[ 48.,  49.],
          [ 54.,  55.]],

         [[ 84.,  85.],
          [ 90.,  91.]]],


        [[[ 14.,  15.],
          [ 20.,  21.]],

         [[ 50.,  51.],
          [ 56.,  57.]],

         [[ 86.,  87.],
          [ 92.,  93.]]],


        [[[ 16.,  17.],
          [ 22.,  23.]],

         [[ 52.,  53.],
          [ 58.,  59.]],

         [[ 88.,  89.],
          [ 94.,  95.]]],


        [[[ 24.,  25.],
          [ 30.,  31.]],

         [[ 60.,  61.],
          

In [132]:
out1= out.permute(1,2,3,0)
print(f"{out1.shape=}")
unfolded_out = out1.view(1,3*2*2,9)
folding = nn.Fold(output_size=(6, 6), kernel_size=(2, 2), stride=(2,2))
folded = folding(unfolded_out)
print(f"{torch.all(folded.eq(x))=}")

out1.shape=torch.Size([3, 2, 2, 9])
torch.all(folded.eq(x))=tensor(True)


In [123]:
[0,2,4]*3

[0, 2, 4, 0, 2, 4, 0, 2, 4]

In [146]:
x = torch.zeros([1,2,3])
x

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [147]:
y=x.clone().detach()

In [148]:
y[0,0,0]=1

In [149]:
x

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])